In [1]:
import numpy as np

In [2]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
np.ones(5)
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.random.rand(2,3)
np.random.randn(2,3)
np.random.randint(0,5, (2,3))
np.random.randint(0,5, 15)

array([2, 2, 4, 4, 3, 2, 0, 4, 3, 1, 2, 2, 2, 2, 4])

In [17]:
np.random.seed(42)
np.random.rand(5)
# Excact Same Random Numbers

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [18]:
arr = np.arange(0,20)

arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
arr = np.random.randint(0,10,5)
print(arr)
arr.min()
arr.max()
arr.argmax()
arr.argmin()

[2 4 2 6 4]


0

In [30]:
arr = np.arange(0,10)
# arr = arr[:6]
arr = arr[6:]
print(arr)

[6 7 8 9]


In [36]:
arrA = np.arange(0,5)
arrB = arrA[0:3].copy()
arrB[:] = 10
print(arrA)

[0 1 2 3 4]


In [44]:
arrC = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arrC[:2, 2:])

[[3]
 [6]]


In [49]:
arrD = np.arange(0,5)
arrD[arrD < 2]

array([0, 1])

In [52]:
arrE = np.arange(0,25).reshape(5,5)
print(arrE)
arrE.sum(axis=1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 10,  35,  60,  85, 110])